# Generated by Django 2.0.7 on 2018-09-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='商品号'),
        ),
    ]
