# Generated by Django 2.0.7 on 2018-09-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180913_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(default='', max_length=300, verbose_name='商品简述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=models.TextField(default='', max_length=800, verbose_name='商品具体情况'),
        ),
    ]
