# Generated by Django 2.0.7 on 2018-11-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181026_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsbrand',
            name='goods_category',
            field=models.ForeignKey(default='', help_text='商品类型', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类型'),
        ),
    ]
