# Generated by Django 2.0.7 on 2018-11-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodsbrand_goods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsbrand',
            name='goods_category',
            field=models.ForeignKey(default='', help_text='商品类型', on_delete=django.db.models.deletion.CASCADE, related_name='goods_band', to='goods.GoodsCategory', verbose_name='商品类型'),
        ),
    ]
