# Generated by Django 2.0.7 on 2018-11-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20181106_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
    ]
