# Generated by Django 2.0.7 on 2018-09-10 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.OrderForm', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='shop_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ShoppingCat', verbose_name='购物车'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
