# Generated by Django 2.0.7 on 2018-11-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180910_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderform',
            name='shop_cat',
        ),
    ]
