# Generated by Django 2.0.7 on 2018-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20181104_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '交易支付成功'), ('TRADE_CLOSED', '未付款交易超时关闭，或支付完成后全额退款'), ('WAIT_BUYER_PAY', '交易创建，等待买家付款'), ('TRADE_FINISHED', '交易结束，不可退款')], default='no_success', max_length=30, verbose_name='支付状态'),
        ),
    ]
