# Generated by Django 2.0.7 on 2018-10-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181009_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecode',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
